### ISSUE TITLE
In README, links to library specs do not work. 

### ISSUE THREAD

**Issue by aaltat** [MarketSquare/robotframework-seleniumlibrary-java#108]
There are two links with this text: 
`For keyword completion in RIDE you can download this Library Specs and place it in your PYTHONPATH.` in the README. But those links are broken and the xml file can not be downloaded.

**Comment by Hi-Fi** [comment]
True, I fixed those only for https://github.com/MarketSquare/robotframework-seleniumlibrary-java/tree/selenium4 branch. Updating develop now, too (most of the changes are selenium4 branch waiting for final version of it to be released)

**Comment by aaltat** [comment]
By the way, to totally different topic. SeleniumLibrary Python dropped Selenium 2 long time ago. Also in the latest release it will only support latest Selenium 3 version. Then it was pretty easy to start supporting Selenium 4.

**Comment by Hi-Fi** [comment]
Java version has basically supported only single Selenium version all the time. That Selenium 2 version hasn't been touched since the release of first Selenium 3 version. 

I thought that Selenium 4 would come a bit faster, but it might be that the current selenium4 branhch changes (more around than because of S4) need to be taken to S3 and same time update many dependencies that are out of date.
