### ISSUE TITLE
Fails to connect to remote browser on Java11

### ISSUE THREAD

**Issue by ghost** [MarketSquare/robotframework-seleniumlibrary-java#61]
Hey,

It seem the lib has issues with latest java. I am enforcing latest robotframework by excluding the current version, but it still fails. Updating the selenium-server to the latest version seems to solve this issue.

I can create a pull request with the updated dependencies for Java11 if you are okay with it, currently it is a bit messy pom wise to exclude and add up-to-date versions.

**Comment by Hi-Fi** [comment]
I think this issue is already solved with the usage of latest versions (both Selenium 3 and 4)? 

At least JBrowserDriver is not compatible with Java 11 and Java 8 at the same time, but otherwise I think library works fine with Java 11. 

Building of library works only from Selenium4 branch, as develop uses too old aspectj plugin.
