### ISSUE TITLE
Turn Hi-Fi account into an organization   

### ISSUE THREAD

**Issue by YauheniPo** [MarketSquare/robotframework-seleniumlibrary-java#96]
why don’t you remake the profile for the organization to promote the library?
https://github.com/settings/organizations

**Comment by Hi-Fi** [comment]
At Robocon2020 there was idea to create new organization for Robot libraries called Market Square (https://github.com/marketsquare). This library is going to be moved to there, and that's going to be used as collective for development. 

Of course same time groupid is going to change, and because of that the first release/SNAPSHOT from there might take a while.

**Comment by YauheniPo** [comment]
awesome!
