### ISSUE TITLE
Open browser with desired capabilities as a dictionnary do not work

### ISSUE THREAD

**Issue by csand83** [MarketSquare/robotframework-seleniumlibrary-java#97]
Hello,

I'm trying to call open browser using a dictionary to give the list of desired capabilities but the parameters are not received correctly by sauce labs.
I've tried the same code exactly with robotframework in python and it's working perfectly.
Could you please check if this should be working ?

Do not hesitate to contact me if you need more info.

Thanks a lot.

Best regards, Christophe

**Comment by Hi-Fi** [comment]
I haven't used Saucelabs at all, but there's a difference in desired capabilities adding between Java and Python version. In Python there's just `desired_capabilities=None`, but in Java there's `desiredCapabilities=None, browserOptions=None` (probably because of Selenium itself).

So same options are not necessarily working, but those has to be adjusted accordingly (or make the change to code to handle things same way, which might be hard because of Selenium differences).

**Comment by Hi-Fi** [comment]
No comments, so closing.
